# Generated by Django 2.0.1 on 2018-06-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('actors', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('popcorn_score', models.IntegerField(blank=True, default=None, null=True)),
                ('tomato_score', models.IntegerField(blank=True, default=None, null=True)),
                ('_release_date', models.DateField(blank=True, db_column='release_date', default=None, max_length=15, null=True)),
                ('runtime', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('poster', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('synopsis', models.TextField(blank=True, default=None, null=True)),
                ('trailer', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('imdb_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('tmdb_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieflix.Movie', to_field='title'),
        ),
    ]
