# Generated by Django 2.0.1 on 2018-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('actors', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('popcorn_score', models.IntegerField(blank=True, default=None, null=True)),
                ('tomato_score', models.IntegerField(blank=True, default=None, null=True)),
                ('release_date', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('runtime', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('poster', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('trailer', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
