# Generated by Django 2.0.1 on 2018-01-02 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('popcorn_score', models.IntegerField()),
                ('tomato_score', models.IntegerField()),
                ('release_date', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=20)),
                ('rated', models.CharField(max_length=10)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
