# Generated by Django 2.0.1 on 2018-01-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite',
        ),
    ]
