# Generated by Django 2.0.1 on 2018-05-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0002_auto_20180506_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
