# Generated by Django 2.0.1 on 2018-01-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0002_remove_movie_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rated',
            new_name='rating',
        ),
    ]
