# Generated by Django 2.0.1 on 2018-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0003_auto_20180102_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
