# Generated by Django 2.0.1 on 2018-05-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0003_movie_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
