# Generated by Django 2.0.1 on 2018-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0005_auto_20180419_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
