# Generated by Django 2.0.1 on 2018-04-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0006_auto_20180419_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=100),
        ),
    ]
